export const PACKAGES = [
  {
    id: "git",
    group: "Core",
    label: "Git",
    note: "Version control and shell integration.",
    presets: ["minimal", "agent"],
    deps: { mac: ["homebrew"], win: [] },
    mac: () => ['brew_formula "Git" "git" "git"'],
    win: () => ["Install-Winget -Label 'Git' -PackageId 'Git.Git' -Command 'git' -ExtraArgs @('--scope','user')"]
  },
  {
    id: "node",
    group: "Core",
    label: "Node.js",
    note: "JavaScript runtime. Required for npm global CLIs.",
    presets: ["minimal", "agent"],
    deps: { mac: ["homebrew"], win: [] },
    mac: () => ['brew_formula "Node.js" "node" "node"'],
    win: () => ["Install-Winget -Label 'Node.js LTS' -PackageId 'OpenJS.NodeJS.LTS' -Command 'node' -ExtraArgs @('--scope','user')"]
  },
  {
    id: "pnpm",
    group: "Core",
    label: "pnpm",
    note: "JavaScript package manager enabled through Corepack, with npm fallback.",
    presets: ["minimal", "agent"],
    deps: { mac: ["node"], win: ["node"] },
    mac: () => ["install_pnpm"],
    win: () => ["Install-Pnpm"]
  },
  {
    id: "python",
    group: "Core",
    label: "Python",
    note: "Latest package-manager stable Python.",
    presets: ["minimal", "agent"],
    deps: { mac: ["homebrew"], win: [] },
    mac: () => ["install_python"],
    win: () => [
      "$pythonOk = $false",
      "foreach ($candidate in @('Python.Python.3.14','Python.Python.3.13','Python.Python.3.12')) {",
      "  if ($pythonOk) { break }",
      "  Install-Winget -Label 'Python' -PackageId $candidate -Command 'python' -ExtraArgs @('--scope','user') -DeferFailure",
      "  if (Has-Command 'python') { $pythonOk = $true }",
      "}",
      "if (-not $pythonOk) { Fail 'Python' }"
    ]
  },
  {
    id: "uv",
    group: "Core",
    label: "uv",
    note: "Python package and project manager.",
    presets: ["minimal", "agent"],
    deps: { mac: [], win: [] },
    mac: () => ["install_uv"],
    win: () => ["Install-Uv"]
  },
  {
    id: "bun",
    group: "Core",
    label: "Bun",
    note: "Optional JavaScript runtime and package manager.",
    presets: [],
    deps: { mac: [], win: [] },
    mac: () => ["install_bun"],
    win: () => ["Install-Bun"]
  },
  {
    id: "docker",
    group: "Core",
    label: "Docker Desktop",
    note: "Container runtime. May require first launch or restart after install.",
    presets: [],
    deps: { mac: ["homebrew"], win: [] },
    mac: () => ['brew_cask "Docker Desktop" "docker" "Docker.app" ""'],
    win: () => ["Install-DockerDesktop"]
  },
  {
    id: "wsl2",
    group: "Core",
    label: "Windows WSL2",
    note: "Windows-only Linux subsystem. May require administrator permission and restart.",
    platforms: ["win"],
    presets: [],
    deps: { mac: [], win: [] },
    win: () => ["Install-WSL2"]
  },
  {
    id: "vscode",
    group: "Editor",
    label: "VS Code",
    note: "Editor and code command.",
    presets: ["agent"],
    deps: { mac: ["homebrew"], win: [] },
    mac: () => ['brew_cask "VS Code" "visual-studio-code" "Visual Studio Code.app" "code"'],
    win: () => ["Install-VSCode"]
  },
  {
    id: "claude-desktop",
    group: "AI tools",
    label: "Claude Desktop",
    note: "Desktop app.",
    presets: ["agent"],
    deps: { mac: ["homebrew"], win: [] },
    mac: () => ['brew_cask "Claude Desktop" "claude" "Claude.app" ""'],
    win: () => ["Install-ClaudeDesktop"]
  },
  {
    id: "claude-code",
    group: "AI tools",
    label: "Claude Code CLI",
    note: "Native installer first, Homebrew or WinGet fallback, npm fallback when available.",
    presets: ["agent"],
    deps: { mac: ["node"], win: ["node"] },
    mac: () => ["install_claude_code"],
    win: () => ["Install-ClaudeCode"]
  },
  {
    id: "claude-code-telemetry",
    group: "AI tools",
    label: "Claude Code CLI telemetry",
    note: "Enables Claude Code OpenTelemetry metrics and logs with redacted prompt text.",
    presets: [],
    deps: { mac: ["claude-code"], win: ["claude-code"] },
    mac: (settings) => [`configure_claude_code_telemetry ${telemetryArgs(settings)}`],
    win: (settings) => [`Set-ClaudeCodeTelemetry ${telemetryArgs(settings, ps)}`]
  },
  {
    id: "claude-extension",
    group: "AI tools",
    label: "Claude Code VS Code extension",
    note: "Installs anthropic.claude-code.",
    presets: ["agent"],
    deps: { mac: ["vscode"], win: ["vscode"] },
    mac: () => ['install_vscode_extension "anthropic.claude-code" "Claude Code VS Code extension"'],
    win: () => ["Install-CodeExtension -ExtensionId 'anthropic.claude-code' -Label 'Claude Code VS Code extension'"]
  },
  {
    id: "codex-app",
    group: "AI tools",
    label: "Codex App",
    note: "Installs the official OpenAI Codex desktop app.",
    presets: [],
    deps: { mac: [], win: [] },
    mac: () => ["install_codex_app"],
    win: () => ["Install-CodexApp"]
  },
  {
    id: "codex",
    group: "AI tools",
    label: "Codex CLI",
    note: "Standalone installer first, Homebrew fallback on macOS, npm fallback when available.",
    presets: [],
    deps: { mac: ["node"], win: ["node"] },
    mac: () => ["install_codex_cli"],
    win: () => ["Install-CodexCli"]
  },
  {
    id: "codex-telemetry",
    group: "AI tools",
    label: "Codex CLI telemetry",
    note: "Writes Codex OpenTelemetry log export config with redacted prompt text.",
    presets: [],
    deps: { mac: ["codex"], win: ["codex"] },
    mac: (settings) => [`configure_codex_telemetry ${telemetryArgs(settings)}`],
    win: (settings) => [`Set-CodexTelemetry ${telemetryArgs(settings, ps)}`]
  },
  {
    id: "vercel",
    group: "Web deploy",
    label: "Vercel CLI",
    note: "Installs vercel with npm.",
    presets: [],
    deps: { mac: ["node"], win: ["node"] },
    mac: () => ['npm_global "Vercel CLI" "vercel" "vercel"'],
    win: () => ["Install-NpmGlobal -Label 'Vercel CLI' -Package 'vercel' -Command 'vercel'"]
  },
  {
    id: "gh",
    group: "Source control",
    label: "GitHub CLI",
    note: "gh command.",
    presets: ["agent"],
    deps: { mac: ["homebrew"], win: [] },
    mac: () => ['brew_formula "GitHub CLI" "gh" "gh"'],
    win: () => ["Install-Winget -Label 'GitHub CLI' -PackageId 'GitHub.cli' -Command 'gh'"]
  },
  {
    id: "github-auth",
    group: "Source control",
    label: "GitHub CLI auth",
    note: "Checks gh login and prints the login command when needed.",
    presets: ["agent"],
    deps: { mac: ["gh"], win: ["gh"] },
    mac: () => ["check_github_auth"],
    win: () => ["Check-GitHubAuth"]
  },
  {
    id: "glab",
    group: "Source control",
    label: "GitLab CLI",
    note: "glab command.",
    presets: [],
    deps: { mac: ["homebrew"], win: [] },
    mac: () => ['brew_formula "GitLab CLI" "glab" "glab"'],
    win: () => ["Install-Winget -Label 'GitLab CLI' -PackageId 'glab.glab' -Command 'glab'"]
  },
  {
    id: "git-config",
    group: "Source control",
    label: "Git identity defaults",
    note: "Writes name and email only when both are missing.",
    presets: [],
    deps: { mac: ["git"], win: ["git"] },
    mac: (settings) => [
      `configure_git ${sh(settings.gitName)} ${sh(settings.gitEmail)}`
    ],
    win: (settings) => [
      `Set-GitDefaults -Name ${ps(settings.gitName)} -Email ${ps(settings.gitEmail)}`
    ]
  }
];

const SYSTEM_LABELS = {
  homebrew: "Homebrew"
};

const packageById = new Map(PACKAGES.map((item) => [item.id, item]));
const DEFAULT_OTEL_ENDPOINT = "http://localhost:4317";

const TELEMETRY_SETTING_KEYS = [
  ["otelEndpoint", DEFAULT_OTEL_ENDPOINT],
  ["otelProtocol", "grpc"],
  ["otelHeaderName", ""],
  ["otelHeaderValue", ""],
  ["otelEnvironment", "dev"],
  ["otelResourceAttributes", ""],
  ["otelMetricInterval", "60000"],
  ["otelLogsInterval", "5000"],
  ["claudeMetricsExporter", "otlp"],
  ["claudeLogsExporter", "otlp"],
  ["claudeTracesExporter", "none"],
  ["claudeLogUserPrompts", false],
  ["claudeLogAssistantResponses", false],
  ["claudeLogToolDetails", false],
  ["claudeLogToolContent", false],
  ["claudeRawApiBodiesMode", "off"],
  ["claudeRawApiBodiesDir", ""],
  ["codexLogExporter", "otlp"],
  ["codexTraceExporter", "none"],
  ["codexMetricsExporter", "none"],
  ["codexLogUserPrompt", false]
];

function sh(value) {
  return `'${String(value).replace(/'/g, `'\\''`)}'`;
}

function ps(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

function boolSetting(settings, key) {
  return settings?.[key] ? "1" : "0";
}

function setting(settings, key, fallback) {
  const value = settings?.[key];
  if (value === undefined || value === null || value === "") {
    return fallback;
  }
  // Strip CR/LF: illegal in TOML basic strings and a script-line breakout vector.
  return typeof value === "string" ? value.replace(/[\r\n]/g, "") : value;
}

function telemetryArgs(settings, quote = sh) {
  return TELEMETRY_SETTING_KEYS.map(([key, fallback]) => {
    const value = typeof fallback === "boolean" ? boolSetting(settings, key) : setting(settings, key, fallback);
    return quote(value);
  }).join(" ");
}

export function fileName(os) {
  return os === "mac" ? "setup-mac.command" : "setup-windows.bat";
}

export function supportsOs(item, os) {
  return !item.platforms || item.platforms.includes(os);
}

export function resolveSelection(ids, os) {
  const resolved = new Set([...ids].filter((id) => {
    const item = packageById.get(id);
    return !item || supportsOs(item, os);
  }));
  let changed = true;
  while (changed) {
    changed = false;
    for (const id of [...resolved]) {
      const item = packageById.get(id);
      if (!item) {
        continue;
      }
      for (const dep of item.deps[os] || []) {
        if (!resolved.has(dep)) {
          resolved.add(dep);
          changed = true;
        }
      }
    }
  }
  return resolved;
}

export function visibleResolved(resolved) {
  return PACKAGES.filter((item) => resolved.has(item.id)).map((item) => item.id);
}

export function autoAdded(original, resolved) {
  return [...resolved].filter((id) => !original.has(id)).map((id) => {
    const item = packageById.get(id);
    return item ? item.label : SYSTEM_LABELS[id] || id;
  });
}

export function buildMacScript(resolved, settings) {
  const body = [];
  if (resolved.has("homebrew")) {
    body.push("install_homebrew");
  }
  for (const id of visibleResolved(resolved)) {
    const item = packageById.get(id);
    if (item.mac) {
      body.push(...item.mac(settings));
    }
  }
  return [
    "#!/bin/bash",
    "# Generated by Dev Setup Builder.",
    "# Run with: bash setup-mac.command",
    "# For Finder double-click: chmod +x setup-mac.command",
    "# If macOS blocks it: right-click the file, choose Open, then Open again.",
    "# If quarantine still blocks it: xattr -d com.apple.quarantine setup-mac.command",
    "set -u",
    "set -o pipefail",
    "",
    'LOG="${TMPDIR:-/tmp}/dev-setup-builder-$(date +%Y%m%d-%H%M%S).log"',
    ': > "$LOG"',
    "FAILED_ITEMS=()",
    "",
    'has() { command -v "$1" >/dev/null 2>&1; }',
    'info() { printf "\\n[%s]\\n" "$1"; }',
    'ok() { printf "  OK: %s\\n" "$1"; }',
    'warn() { printf "  WARN: %s\\n" "$1"; }',
    'fail() { printf "  FAIL: %s\\n" "$1"; FAILED_ITEMS+=("$1"); }',
    "",
    "path_prepend() {",
    '  [ -d "$1" ] || return 0',
    '  case ":${PATH:-}:" in *":$1:"*) ;; *) export PATH="$1:${PATH:-}" ;; esac',
    "}",
    "",
    "refresh_path() {",
    "  if has brew; then",
    '    eval "$(brew shellenv)"',
    "  elif [ -x /opt/homebrew/bin/brew ]; then",
    '    eval "$(/opt/homebrew/bin/brew shellenv)"',
    "  elif [ -x /usr/local/bin/brew ]; then",
    '    eval "$(/usr/local/bin/brew shellenv)"',
    "  fi",
    '  path_prepend "$HOME/.bun/bin"',
    '  path_prepend "$HOME/.local/bin"',
    '  path_prepend "/Applications/Visual Studio Code.app/Contents/Resources/app/bin"',
    '  path_prepend "$HOME/Applications/Visual Studio Code.app/Contents/Resources/app/bin"',
    "  if has npm; then",
    '    prefix="$(npm prefix -g 2>/dev/null || true)"',
    '    [ -n "$prefix" ] && path_prepend "$prefix/bin"',
    "  fi",
    "}",
    "",
    "append_once() {",
    '  file="$1"; marker="$2"; shift 2',
    '  mkdir -p "$(dirname "$file")"; touch "$file"',
    '  grep -Fq "$marker" "$file" 2>/dev/null && return 0',
    '  { printf "\\n%s\\n" "$marker"; for line in "$@"; do printf "%s\\n" "$line"; done; } >> "$file"',
    "}",
    "",
    "install_homebrew() {",
    '  info "Homebrew"',
    "  if has brew; then ok \"Homebrew installed\"; refresh_path; return 0; fi",
    "  # Official install docs: https://brew.sh/",
    "  # NONINTERACTIVE=1 skips the RETURN prompt; output stays on the terminal so the sudo password prompt is visible.",
    `  NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" || { fail "Homebrew"; return 1; }`,
    "  refresh_path",
    '  if has brew; then ok "Homebrew installed"; else fail "Homebrew"; fi',
    "}",
    "",
    "brew_formula() {",
    '  label="$1"; formula="$2"; command_name="$3"',
    '  info "$label"',
    '  if has "$command_name"; then ok "$label installed"; return 0; fi',
    '  if ! has brew; then fail "$label (Homebrew missing)"; return 1; fi',
    "  # Homebrew formula docs: https://docs.brew.sh/Formula-Cookbook",
    '  brew install "$formula" >> "$LOG" 2>&1',
    "  refresh_path",
    '  if has "$command_name"; then ok "$label installed"; else fail "$label"; fi',
    "}",
    "",
    "install_python() {",
    '  info "Python"',
    "  # /usr/bin/python3 is an Apple CommandLineTools stub, so check for a real Homebrew Python instead of `has python3`.",
    '  if [ -x /opt/homebrew/bin/python3 ] || [ -x /usr/local/bin/python3 ]; then ok "Python installed"; return 0; fi',
    '  if ! has brew; then fail "Python (Homebrew missing)"; return 1; fi',
    '  brew install python >> "$LOG" 2>&1',
    "  refresh_path",
    '  if [ -x /opt/homebrew/bin/python3 ] || [ -x /usr/local/bin/python3 ]; then ok "Python installed"; else fail "Python"; fi',
    "}",
    "",
    "app_exists() {",
    '  [ -n "$1" ] && { [ -d "/Applications/$1" ] || [ -d "$HOME/Applications/$1" ]; }',
    "}",
    "",
    "cask_installed() {",
    '  [ -n "$1" ] && has brew && brew list --cask "$1" >/dev/null 2>&1',
    "}",
    "",
    "brew_cask() {",
    '  label="$1"; cask="$2"; app_name="$3"; command_name="$4"',
    '  info "$label"',
    '  [ -n "$command_name" ] && has "$command_name" && { ok "$label installed"; return 0; }',
    '  { app_exists "$app_name" || cask_installed "$cask"; } && { ok "$label installed"; return 0; }',
    '  if ! has brew; then fail "$label (Homebrew missing)"; return 1; fi',
    "  # Homebrew cask docs: https://docs.brew.sh/Cask-Cookbook",
    '  brew install --cask "$cask" >> "$LOG" 2>&1',
    "  refresh_path",
    '  if { [ -n "$command_name" ] && has "$command_name"; } || app_exists "$app_name" || cask_installed "$cask"; then ok "$label installed"; else fail "$label"; fi',
    "}",
    "",
    "npm_global() {",
    '  label="$1"; package_name="$2"; command_name="$3"',
    '  info "$label"',
    '  if has "$command_name"; then ok "$label installed"; return 0; fi',
    '  if ! has npm; then fail "$label (npm missing)"; return 1; fi',
    "  # npm install docs: https://docs.npmjs.com/cli/commands/npm-install",
    '  npm install -g "$package_name" >> "$LOG" 2>&1',
    "  refresh_path",
    '  if has "$command_name"; then ok "$label installed"; else fail "$label"; fi',
    "}",
    "",
    "install_pnpm() {",
    '  info "pnpm"',
    '  if has pnpm; then ok "pnpm installed"; return 0; fi',
    "  # Official install docs: https://pnpm.io/installation",
    '  if has corepack; then corepack enable >> "$LOG" 2>&1; corepack prepare pnpm@latest --activate >> "$LOG" 2>&1; refresh_path; fi',
    '  if ! has pnpm && has npm; then npm install -g pnpm >> "$LOG" 2>&1; refresh_path; fi',
    '  if has pnpm; then ok "pnpm installed"; else fail "pnpm"; fi',
    "}",
    "",
    "install_bun() {",
    '  info "Bun"',
    '  if has bun || [ -x "$HOME/.bun/bin/bun" ]; then path_prepend "$HOME/.bun/bin"; ok "Bun installed"; return 0; fi',
    "  # Official install docs: https://bun.com/docs/installation",
    '  curl -fsSL https://bun.sh/install | bash >> "$LOG" 2>&1',
    '  path_prepend "$HOME/.bun/bin"',
    '  append_once "$HOME/.zprofile" "# Dev Setup Builder - Bun PATH" \'export BUN_INSTALL="$HOME/.bun"\' \'export PATH="$BUN_INSTALL/bin:$PATH"\'',
    '  if has bun || [ -x "$HOME/.bun/bin/bun" ]; then ok "Bun installed"; else fail "Bun"; fi',
    "}",
    "",
    "install_uv() {",
    '  info "uv"',
    '  if has uv || [ -x "$HOME/.local/bin/uv" ]; then path_prepend "$HOME/.local/bin"; ok "uv installed"; return 0; fi',
    "  # Official install docs: https://docs.astral.sh/uv/getting-started/installation/",
    '  curl -LsSf https://astral.sh/uv/install.sh | sh >> "$LOG" 2>&1',
    '  path_prepend "$HOME/.local/bin"',
    '  append_once "$HOME/.zprofile" "# Dev Setup Builder - uv PATH" \'export PATH="$HOME/.local/bin:$PATH"\'',
    '  if has uv || [ -x "$HOME/.local/bin/uv" ]; then ok "uv installed"; else fail "uv"; fi',
    "}",
    "",
    "install_claude_code() {",
    '  info "Claude Code CLI"',
    '  if has claude; then ok "Claude Code CLI installed"; return 0; fi',
    "  # Official install docs: https://docs.anthropic.com/en/docs/claude-code/setup",
    '  { curl -fsSL https://claude.ai/install.sh | bash; } >> "$LOG" 2>&1',
    "  refresh_path",
    '  if has claude; then ok "Claude Code CLI installed"; return 0; fi',
    '  if has brew; then brew install --cask claude-code >> "$LOG" 2>&1; refresh_path; fi',
    '  if has claude; then ok "Claude Code CLI installed"; return 0; fi',
    '  if has npm; then npm_global "Claude Code CLI" "@anthropic-ai/claude-code" "claude"; else fail "Claude Code CLI"; fi',
    "}",
    "",
    "install_codex_cli() {",
    '  info "Codex CLI"',
    '  if has codex; then ok "Codex CLI installed"; return 0; fi',
    "  # Official install docs: https://developers.openai.com/codex/quickstart",
    '  { curl -fsSL https://chatgpt.com/codex/install.sh | CODEX_NON_INTERACTIVE=1 sh; } >> "$LOG" 2>&1',
    "  refresh_path",
    '  if has codex; then ok "Codex CLI installed"; return 0; fi',
    '  if has brew; then brew install --cask codex >> "$LOG" 2>&1; refresh_path; fi',
    '  if has codex; then ok "Codex CLI installed"; return 0; fi',
    '  if has npm; then npm_global "Codex CLI" "@openai/codex" "codex"; else fail "Codex CLI"; fi',
    "}",
    "",
    "install_codex_app() {",
    '  info "Codex App"',
    '  app_exists "Codex.app" && { ok "Codex App installed"; return 0; }',
    "  # Official install docs: https://developers.openai.com/codex/app",
    '  url="https://persistent.oaistatic.com/codex-app-prod/Codex.dmg"',
    '  [ "$(uname -m)" = "x86_64" ] && url="https://persistent.oaistatic.com/codex-app-prod/Codex-latest-x64.dmg"',
    '  tmp_dmg="${TMPDIR:-/tmp}/codex-app-$$.dmg"',
    '  mount_dir="$(mktemp -d "${TMPDIR:-/tmp}/codex-app.XXXXXX")"',
    '  cleanup_codex_app() { hdiutil detach "$mount_dir" >/dev/null 2>&1 || true; rm -f "$tmp_dmg"; rmdir "$mount_dir" 2>/dev/null || true; }',
    '  curl -fL "$url" -o "$tmp_dmg" >> "$LOG" 2>&1 || { fail "Codex App download"; cleanup_codex_app; return 1; }',
    '  hdiutil attach "$tmp_dmg" -mountpoint "$mount_dir" -nobrowse -quiet >> "$LOG" 2>&1 || { fail "Codex App mount"; cleanup_codex_app; return 1; }',
    '  source_app="$(find "$mount_dir" -maxdepth 2 -name "Codex.app" -type d | head -n 1)"',
    '  [ -n "$source_app" ] || source_app="$(find "$mount_dir" -maxdepth 2 -name "*.app" -type d | head -n 1)"',
    '  [ -n "$source_app" ] || { fail "Codex App image"; cleanup_codex_app; return 1; }',
    '  app_name="$(basename "$source_app")"',
    '  target_dir="/Applications"',
    '  [ -w "$target_dir" ] || target_dir="$HOME/Applications"',
    '  mkdir -p "$target_dir"',
    '  rm -rf "$target_dir/$app_name"',
    '  cp -R "$source_app" "$target_dir/" >> "$LOG" 2>&1',
    '  cleanup_codex_app',
    '  if app_exists "$app_name"; then ok "Codex App installed"; else fail "Codex App"; fi',
    "}",
    "",
    "configure_claude_code_telemetry() {",
    '  endpoint="$1"; protocol="$2"; header_name="$3"; header_value="$4"; environment="$5"; resource_attrs="$6"',
    '  metric_interval="$7"; logs_interval="$8"; metrics_exporter="$9"; logs_exporter="${10}"; traces_exporter="${11}"',
    '  log_prompts="${12}"; log_assistant="${13}"; log_tool_details="${14}"; log_tool_content="${15}"; raw_mode="${16}"; raw_dir="${17}"',
    '  info "Claude Code CLI telemetry"',
    '  telemetry_file="$HOME/.config/dev-setup-builder/claude-code-telemetry.sh"',
    '  mkdir -p "$(dirname "$telemetry_file")"',
    '  combined_attrs="deployment.environment=$environment"',
    '  [ -n "$resource_attrs" ] && combined_attrs="$combined_attrs,$resource_attrs"',
    "  {",
    '    printf "%s\\n" "# Generated by Dev Setup Builder."',
    '    printf "%s\\n" "export CLAUDE_CODE_ENABLE_TELEMETRY=1"',
    '    printf "export OTEL_METRICS_EXPORTER=%s\\n" "$(shell_escape "$metrics_exporter")"',
    '    printf "export OTEL_LOGS_EXPORTER=%s\\n" "$(shell_escape "$logs_exporter")"',
    '    printf "export OTEL_EXPORTER_OTLP_PROTOCOL=%s\\n" "$(shell_escape "$protocol")"',
    '    printf "export OTEL_EXPORTER_OTLP_ENDPOINT=%s\\n" "$(shell_escape "$endpoint")"',
    '    printf "export OTEL_RESOURCE_ATTRIBUTES=%s\\n" "$(shell_escape "$combined_attrs")"',
    '    printf "export OTEL_METRIC_EXPORT_INTERVAL=%s\\n" "$(shell_escape "$metric_interval")"',
    '    printf "export OTEL_LOGS_EXPORT_INTERVAL=%s\\n" "$(shell_escape "$logs_interval")"',
    '    printf "export OTEL_LOG_USER_PROMPTS=%s\\n" "$(shell_escape "$log_prompts")"',
    '    printf "export OTEL_LOG_ASSISTANT_RESPONSES=%s\\n" "$(shell_escape "$log_assistant")"',
    '    printf "export OTEL_LOG_TOOL_DETAILS=%s\\n" "$(shell_escape "$log_tool_details")"',
    '    printf "export OTEL_LOG_TOOL_CONTENT=%s\\n" "$(shell_escape "$log_tool_content")"',
    '    [ "$traces_exporter" != "none" ] && printf "%s\\n" "export CLAUDE_CODE_ENHANCED_TELEMETRY_BETA=1"',
    '    printf "export OTEL_TRACES_EXPORTER=%s\\n" "$(shell_escape "$traces_exporter")"',
    '    [ -n "$header_name" ] && [ -n "$header_value" ] && printf "export OTEL_EXPORTER_OTLP_HEADERS=%s\\n" "$(shell_escape "$header_name=$header_value")"',
    '    [ "$raw_mode" = "inline" ] && printf "%s\\n" "export OTEL_LOG_RAW_API_BODIES=1"',
    '    [ "$raw_mode" = "file" ] && [ -n "$raw_dir" ] && printf "export OTEL_LOG_RAW_API_BODIES=%s\\n" "$(shell_escape "file:$raw_dir")"',
    '  } > "$telemetry_file"',
    '  chmod 600 "$telemetry_file"',
    '  append_once "$HOME/.zshrc" "# Dev Setup Builder - Claude Code telemetry" "source \\"$telemetry_file\\""',
    '  ok "Claude Code telemetry configured"',
    "}",
    "",
    "shell_escape() {",
    '  printf "%q" "$1"',
    "}",
    "",
    "toml_escape() {",
    '  printf "%s" "$1" | sed \'s/\\\\/\\\\\\\\/g; s/"/\\\\"/g\'',
    "}",
    "",
    "remove_marked_block() {",
    '  file="$1"; start="$2"; end="$3"; out="$4"',
    '  [ -f "$file" ] || { : > "$out"; return 0; }',
    '  awk -v start="$start" -v end="$end" \'$0 == start { skip = 1; next } $0 == end { skip = 0; next } !skip { print }\' "$file" > "$out"',
    "}",
    "",
    "codex_exporter_toml() {",
    '  kind="$1"; endpoint="$2"; protocol="$3"; header_name="$4"; header_value="$5"',
    '  if [ "$kind" = "none" ] || [ "$kind" = "statsig" ]; then printf "\\"%s\\"" "$kind"; return 0; fi',
    '  safe_endpoint="$(toml_escape "$endpoint")"',
    '  headers=""',
    '  if [ -n "$header_name" ] && [ -n "$header_value" ]; then headers=", headers = { \\"$(toml_escape "$header_name")\\" = \\"$(toml_escape "$header_value")\\" }"; fi',
    '  if [ "$protocol" = "grpc" ]; then',
    '    printf "{ otlp-grpc = { endpoint = \\"%s\\"%s } }" "$safe_endpoint" "$headers"',
    '  else',
    '    http_protocol="binary"; [ "$protocol" = "http/json" ] && http_protocol="json"',
    '    printf "{ otlp-http = { endpoint = \\"%s\\", protocol = \\"%s\\"%s } }" "$safe_endpoint" "$http_protocol" "$headers"',
    '  fi',
    "}",
    "",
    "configure_codex_telemetry() {",
    '  endpoint="$1"; protocol="$2"; header_name="$3"; header_value="$4"; environment="$5"',
    '  log_exporter="${18}"; trace_exporter="${19}"; metrics_exporter="${20}"; log_prompt="${21}"',
    '  info "Codex CLI telemetry"',
    '  config="$HOME/.codex/config.toml"',
    '  mkdir -p "$(dirname "$config")"; touch "$config"',
    '  start="# Dev Setup Builder - Codex telemetry start"; end="# Dev Setup Builder - Codex telemetry end"',
    '  clean="$(mktemp)"',
    '  remove_marked_block "$config" "$start" "$end" "$clean"',
    '  if grep -Eq "^\\[otel\\]" "$clean"; then warn "Codex [otel] already exists outside Dev Setup Builder block; leaving it unchanged"; rm -f "$clean"; return 0; fi',
    '  safe_endpoint="$(toml_escape "$endpoint")"',
    "  {",
    '    cat "$clean"',
    '    printf "\\n%s\\n" "$start"',
    '    printf "[otel]\\n"',
    '    printf "environment = \\"%s\\"\\n" "$(toml_escape "$environment")"',
    '    [ "$log_prompt" = "1" ] && printf "log_user_prompt = true\\n" || printf "log_user_prompt = false\\n"',
    '    printf "exporter = %s\\n" "$(codex_exporter_toml "$log_exporter" "$endpoint" "$protocol" "$header_name" "$header_value")"',
    '    printf "trace_exporter = %s\\n" "$(codex_exporter_toml "$trace_exporter" "$endpoint" "$protocol" "$header_name" "$header_value")"',
    '    printf "metrics_exporter = %s\\n" "$(codex_exporter_toml "$metrics_exporter" "$endpoint" "$protocol" "$header_name" "$header_value")"',
    '    printf "%s\\n" "$end"',
    '  } > "$config"',
    '  rm -f "$clean"',
    '  ok "Codex telemetry configured"',
    "}",
    "",
    "check_github_auth() {",
    '  info "GitHub CLI auth"',
    '  if ! has gh; then fail "GitHub CLI auth (gh missing)"; return 1; fi',
    '  if gh auth status >> "$LOG" 2>&1; then ok "GitHub CLI authenticated"; else warn "GitHub CLI not authenticated. Run: gh auth login -w"; fi',
    "}",
    "",
    "install_vscode_extension() {",
    '  extension_id="$1"; label="$2"',
    '  info "$label"',
    '  if ! has code; then fail "$label (code command missing)"; return 1; fi',
    '  if code --list-extensions 2>/dev/null | grep -qi "^${extension_id}$"; then ok "$label installed"; return 0; fi',
    '  code --install-extension "$extension_id" --force >> "$LOG" 2>&1',
    '  if code --list-extensions 2>/dev/null | grep -qi "^${extension_id}$"; then ok "$label installed"; else fail "$label"; fi',
    "}",
    "",
    "configure_git() {",
    '  name="$1"; email="$2"',
    '  info "Git identity defaults"',
    '  if ! has git; then fail "Git identity defaults (git missing)"; return 1; fi',
    '  existing_name="$(git config --global user.name 2>/dev/null || true)"',
    '  existing_email="$(git config --global user.email 2>/dev/null || true)"',
    '  if [ -n "$existing_name" ] && [ -n "$existing_email" ]; then ok "Git identity already set"; return 0; fi',
    '  [ -z "$existing_name" ] && git config --global user.name "$name" >> "$LOG" 2>&1',
    '  [ -z "$existing_email" ] && git config --global user.email "$email" >> "$LOG" 2>&1',
    '  ok "Git identity defaults set"',
    "}",
    "",
    "refresh_path",
    "",
    ...body,
    "",
    'printf "\\nLog: %s\\n" "$LOG"',
    'if [ "${#FAILED_ITEMS[@]}" -gt 0 ]; then',
    '  printf "Failed items:\\n"',
    '  printf "  - %s\\n" "${FAILED_ITEMS[@]}"',
    "  exit 1",
    "fi",
    'printf "Done. Open a new terminal before using newly installed commands.\\n"'
  ].join("\n");
}

export function buildWindowsScript(resolved, settings) {
  const body = [];
  for (const id of visibleResolved(resolved)) {
    const item = packageById.get(id);
    if (item.win) {
      body.push(...item.win(settings));
    }
  }
  return [
    "@echo off",
    "rem Generated by Dev Setup Builder.",
    "rem If Windows blocks it: right-click file > Properties > Unblock.",
    "rem For installer permission failures: right-click > Run as administrator.",
    "rem For SmartScreen: More info > Run anyway.",
    "setlocal",
    "set \"BAT_FILE=%~f0\"",
    "powershell -NoProfile -ExecutionPolicy Bypass -Command \"$raw=[IO.File]::ReadAllText($env:BAT_FILE,[Text.UTF8Encoding]::new($false)); $m='#__PS_SCRIPT'+'_BELOW__'; $i=$raw.IndexOf($m); if($i -lt 0){ Write-Host 'ERROR: PS marker not found'; exit 1 }; $ps=$raw.Substring($i+$m.Length); $sb=[scriptblock]::Create($ps); & $sb; exit $LASTEXITCODE\"",
    "set \"EC=%ERRORLEVEL%\"",
    "pause",
    "exit /b %EC%",
    "",
    "#__PS_SCRIPT_BELOW__",
    "$ErrorActionPreference = 'Continue'",
    "$ProgressPreference = 'SilentlyContinue'",
    "try { chcp 65001 > $null } catch {}",
    "try { [Console]::OutputEncoding = [Text.UTF8Encoding]::new($false); $OutputEncoding = [Text.UTF8Encoding]::new($false) } catch {}",
    "$LogFile = Join-Path $env:TEMP (\"dev-setup-builder-{0}.log\" -f (Get-Date -Format 'yyyyMMdd-HHmmss'))",
    "[IO.File]::WriteAllText($LogFile, \"=== $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') ===`r`n\", [Text.UTF8Encoding]::new($false))",
    "$script:Failed = @()",
    "",
    "function Ok([string]$Text) { Write-Host \"  OK: $Text\" }",
    "function Warn([string]$Text) { Write-Host \"  WARN: $Text\" }",
    "function Fail([string]$Text) { Write-Host \"  FAIL: $Text\"; $script:Failed += $Text }",
    "function Step([string]$Text) { Write-Host \"\"; Write-Host \"[$Text]\" }",
    "function Has-Command([string]$Name) {",
    "  $commands = @(Get-Command $Name -All -ErrorAction SilentlyContinue)",
    "  if ($Name -ne 'python') { return $commands.Count -gt 0 }",
    "  foreach ($command in $commands) {",
    "    if (-not $command.Source -or -not (Test-Path $command.Source -PathType Leaf)) { continue }",
    "    try { & $command.Source --version *> $null; if ($LASTEXITCODE -eq 0) { return $true } } catch {}",
    "  }",
    "  return $false",
    "}",
    "",
    "function Refresh-Path {",
    "  $machine = [Environment]::GetEnvironmentVariable('Path', 'Machine')",
    "  $user = [Environment]::GetEnvironmentVariable('Path', 'User')",
    "  $seen = [Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)",
    "  $env:Path = (@($env:Path, $machine, $user) -split ';' | Where-Object { $_ -and $seen.Add($_) }) -join ';'",
    "  foreach ($p in @(",
    "    'C:\\Program Files\\Git\\cmd',",
    "    'C:\\Program Files\\Git\\bin',",
    "    'C:\\Program Files\\nodejs',",
    "    'C:\\Program Files\\Docker\\Docker\\resources\\bin',",
    "    (Join-Path $env:APPDATA 'npm'),",
    "    (Join-Path $env:USERPROFILE '.bun\\bin'),",
    "    (Join-Path $env:USERPROFILE '.local\\bin'),",
    "    (Join-Path $env:LOCALAPPDATA 'Microsoft\\WinGet\\Links'),",
    "    (Join-Path $env:LOCALAPPDATA 'Programs\\Microsoft VS Code\\bin')",
    "  )) {",
    "    if ($p -and (Test-Path $p) -and ($env:Path -notlike \"*$p*\")) { $env:Path = \"$p;$env:Path\" }",
    "  }",
    "}",
    "",
    "function Install-Winget {",
    "  param([string]$Label, [string]$PackageId, [string]$Command, [string[]]$ExtraArgs = @(), [switch]$DeferFailure)",
    "  Step $Label",
    "  if ($Command -and (Has-Command $Command)) { Ok \"$Label installed\"; return }",
    "  if (-not (Has-Command 'winget')) { if (-not $DeferFailure) { Fail \"$Label (winget missing)\" }; return }",
    "  # Official winget docs: https://learn.microsoft.com/windows/package-manager/winget/",
    "  $args = @('install','--id',$PackageId,'--exact','--source','winget','--accept-source-agreements','--accept-package-agreements','--silent','--disable-interactivity') + $ExtraArgs",
    "  & winget @args *>> $LogFile",
    "  $exitCode = $LASTEXITCODE",
    "  Refresh-Path",
    "  if ($Command) {",
    "    if (Has-Command $Command) { Ok \"$Label installed\" } elseif (-not $DeferFailure) { Fail $Label }",
    "  } elseif ($exitCode -eq 0) {",
    "    Ok \"$Label installer completed\"",
    "  } elseif (-not $DeferFailure) {",
    "    Fail $Label",
    "  }",
    "}",
    "",
    "function Install-NpmGlobal {",
    "  param([string]$Label, [string]$Package, [string]$Command)",
    "  Step $Label",
    "  if (Has-Command $Command) { Ok \"$Label installed\"; return }",
    "  if (-not (Has-Command 'npm')) { Fail \"$Label (npm missing)\"; return }",
    "  # npm install docs: https://docs.npmjs.com/cli/commands/npm-install",
    "  & npm install -g $Package *>> $LogFile",
    "  Refresh-Path",
    "  if (Has-Command $Command) { Ok \"$Label installed\" } else { Fail $Label }",
    "}",
    "",
    "function Install-Pnpm {",
    "  Step 'pnpm'",
    "  if (Has-Command 'pnpm') { Ok 'pnpm installed'; return }",
    "  # Official install docs: https://pnpm.io/installation",
    "  if (Has-Command 'corepack') { & corepack enable *>> $LogFile; & corepack prepare pnpm@latest --activate *>> $LogFile; Refresh-Path }",
    "  if ((-not (Has-Command 'pnpm')) -and (Has-Command 'npm')) { & npm install -g pnpm *>> $LogFile; Refresh-Path }",
    "  if (Has-Command 'pnpm') { Ok 'pnpm installed' } else { Fail 'pnpm' }",
    "}",
    "",
    "function Test-Admin {",
    "  $identity = [Security.Principal.WindowsIdentity]::GetCurrent()",
    "  $principal = [Security.Principal.WindowsPrincipal]::new($identity)",
    "  return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)",
    "}",
    "",
    "function Install-WSL2 {",
    "  Step 'Windows WSL2'",
    "  if (Has-Command 'wsl') { & wsl --status *>> $LogFile; if ($LASTEXITCODE -eq 0) { Ok 'WSL2 available'; return } }",
    "  if (-not (Test-Admin)) { Fail 'WSL2 (run as administrator)'; return }",
    "  # Official install docs: https://learn.microsoft.com/windows/wsl/install",
    "  & wsl --install --no-launch *>> $LogFile",
    "  $exitCode = $LASTEXITCODE",
    "  if ($exitCode -eq 0) { Ok 'WSL2 install started; restart may be required' } else { Fail 'WSL2' }",
    "}",
    "",
    "function Install-Bun {",
    "  Step 'Bun'",
    "  $bunPath = Join-Path $env:USERPROFILE '.bun\\bin\\bun.exe'",
    "  if ((Has-Command 'bun') -or (Test-Path $bunPath)) { Ok 'Bun installed'; return }",
    "  $installer = Join-Path $env:TEMP 'bun-install.ps1'",
    "  # Official install docs: https://bun.com/docs/installation",
    "  try { Invoke-RestMethod https://bun.sh/install.ps1 -UseBasicParsing -OutFile $installer; & powershell.exe -NoProfile -ExecutionPolicy Bypass -File $installer *>> $LogFile } catch { $_ | Out-String | Add-Content -Path $LogFile }",
    "  Refresh-Path",
    "  if ((Has-Command 'bun') -or (Test-Path $bunPath)) { Ok 'Bun installed' } else { Fail 'Bun' }",
    "}",
    "",
    "function Install-Uv {",
    "  Step 'uv'",
    "  $uvPath = Join-Path $env:USERPROFILE '.local\\bin\\uv.exe'",
    "  if ((Has-Command 'uv') -or (Test-Path $uvPath)) { Ok 'uv installed'; return }",
    "  $installer = Join-Path $env:TEMP 'uv-install.ps1'",
    "  # Official install docs: https://docs.astral.sh/uv/getting-started/installation/",
    "  try { Invoke-RestMethod https://astral.sh/uv/install.ps1 -UseBasicParsing -OutFile $installer; & powershell.exe -NoProfile -ExecutionPolicy Bypass -File $installer *>> $LogFile } catch { $_ | Out-String | Add-Content -Path $LogFile }",
    "  Refresh-Path",
    "  if ((Has-Command 'uv') -or (Test-Path $uvPath)) { Ok 'uv installed' } else { Fail 'uv' }",
    "}",
    "",
    "function Find-Code {",
    "  $cmd = Get-Command code -ErrorAction SilentlyContinue",
    "  if ($cmd) { return $cmd.Source }",
    "  foreach ($p in @(",
    "    (Join-Path $env:LOCALAPPDATA 'Programs\\Microsoft VS Code\\bin\\code.cmd'),",
    "    (Join-Path $env:ProgramFiles 'Microsoft VS Code\\bin\\code.cmd')",
    "  )) { if ($p -and (Test-Path $p)) { return $p } }",
    "  return $null",
    "}",
    "",
    "$script:vscodeCmd = $null",
    "function Install-VSCode {",
    "  Step 'VS Code'",
    "  $script:vscodeCmd = Find-Code",
    "  if ($script:vscodeCmd) { Ok 'VS Code installed'; return }",
    "  # Official install docs: https://code.visualstudio.com/docs/setup/windows",
    "  Install-Winget -Label 'VS Code' -PackageId 'Microsoft.VisualStudioCode' -Command 'code' -ExtraArgs @('--scope','user')",
    "  $script:vscodeCmd = Find-Code",
    "  if (-not $script:vscodeCmd) { Fail 'VS Code command' }",
    "}",
    "",
    "function Test-ClaudeDesktop {",
    "  foreach ($p in @(",
    "    (Join-Path $env:LOCALAPPDATA 'AnthropicClaude\\claude.exe'),",
    "    (Join-Path $env:LOCALAPPDATA 'Programs\\claude-desktop\\Claude.exe'),",
    "    (Join-Path $env:ProgramFiles 'Claude\\Claude.exe')",
    "  )) { if ($p -and (Test-Path $p)) { return $true } }",
    "  try { if (Get-AppxPackage -Name 'Claude' -ErrorAction SilentlyContinue) { return $true } } catch {}",
    "  return $false",
    "}",
    "",
    "function Test-DockerDesktop {",
    "  return [bool](Test-Path (Join-Path $env:ProgramFiles 'Docker\\Docker\\Docker Desktop.exe'))",
    "}",
    "",
    "function Install-DockerDesktop {",
    "  Step 'Docker Desktop'",
    "  if (Test-DockerDesktop) { Ok 'Docker Desktop installed'; return }",
    "  if (-not (Has-Command 'winget')) { Fail 'Docker Desktop (winget missing)'; return }",
    "  # Official install docs: https://docs.docker.com/desktop/setup/install/windows-install/",
    "  & winget install --id Docker.DockerDesktop --exact --source winget --accept-source-agreements --accept-package-agreements --silent --disable-interactivity *>> $LogFile",
    "  $exitCode = $LASTEXITCODE",
    "  Refresh-Path",
    "  if (Test-DockerDesktop) { Ok 'Docker Desktop installed'; return }",
    "  if ($exitCode -eq 0) { Ok 'Docker Desktop installer completed; restart or first launch may be required' } else { Fail 'Docker Desktop' }",
    "}",
    "",
    "function Install-ClaudeDesktop {",
    "  Step 'Claude Desktop'",
    "  if (Test-ClaudeDesktop) { Ok 'Claude Desktop installed'; return }",
    "  # Official download docs: https://claude.ai/download",
    "  Install-Winget -Label 'Claude Desktop' -PackageId 'Anthropic.Claude' -Command '' -ExtraArgs @('--scope','user')",
    "  if (-not (Test-ClaudeDesktop)) { Warn 'Claude Desktop may require a new terminal or manual install' }",
    "}",
    "",
    "function Install-ClaudeCode {",
    "  Step 'Claude Code CLI'",
    "  if (Has-Command 'claude') { Ok 'Claude Code CLI installed'; return }",
    "  # Official install docs: https://docs.anthropic.com/en/docs/claude-code/setup",
    "  try { & powershell.exe -NoProfile -ExecutionPolicy Bypass -Command \"irm https://claude.ai/install.ps1 | iex\" *>> $LogFile } catch { $_ | Out-String | Add-Content -Path $LogFile }",
    "  Refresh-Path",
    "  if (Has-Command 'claude') { Ok 'Claude Code CLI installed'; return }",
    "  if (Has-Command 'winget') { & winget install --id Anthropic.ClaudeCode --exact --source winget --accept-source-agreements --accept-package-agreements --silent --disable-interactivity *>> $LogFile; Refresh-Path }",
    "  if (Has-Command 'claude') { Ok 'Claude Code CLI installed'; return }",
    "  if (Has-Command 'npm') { Install-NpmGlobal -Label 'Claude Code CLI' -Package '@anthropic-ai/claude-code' -Command 'claude' } else { Fail 'Claude Code CLI' }",
    "}",
    "",
    "function Install-CodexCli {",
    "  Step 'Codex CLI'",
    "  if (Has-Command 'codex') { Ok 'Codex CLI installed'; return }",
    "  # Official install docs: https://developers.openai.com/codex/quickstart",
    "  # Set the env var in this scope (inherited by the child) so it is not interpolated away inside the child -Command string.",
    "  $env:CODEX_NON_INTERACTIVE = '1'",
    "  try { & powershell.exe -NoProfile -ExecutionPolicy Bypass -Command \"irm https://chatgpt.com/codex/install.ps1 | iex\" *>> $LogFile } catch { $_ | Out-String | Add-Content -Path $LogFile }",
    "  Refresh-Path",
    "  if (Has-Command 'codex') { Ok 'Codex CLI installed'; return }",
    "  if (Has-Command 'npm') { Install-NpmGlobal -Label 'Codex CLI' -Package '@openai/codex' -Command 'codex' } else { Fail 'Codex CLI' }",
    "}",
    "",
    "function Test-CodexApp {",
    "  foreach ($p in @(",
    "    (Join-Path $env:LOCALAPPDATA 'Programs\\Codex\\Codex.exe'),",
    "    (Join-Path $env:ProgramFiles 'Codex\\Codex.exe')",
    "  )) { if ($p -and (Test-Path $p)) { return $true } }",
    "  try { if (Get-AppxPackage -ErrorAction SilentlyContinue | Where-Object { $_.Name -like '*Codex*' -or $_.PackageFamilyName -like '*Codex*' }) { return $true } } catch {}",
    "  return $false",
    "}",
    "",
    "function Install-CodexApp {",
    "  Step 'Codex App'",
    "  if (Test-CodexApp) { Ok 'Codex App installed'; return }",
    "  if (-not (Has-Command 'winget')) { Fail 'Codex App (winget missing)'; return }",
    "  # Official install docs: https://developers.openai.com/codex/app/windows",
    "  & winget install --id 9PLM9XGG6VKS --exact --source msstore --accept-source-agreements --accept-package-agreements --silent --disable-interactivity *>> $LogFile",
    "  $exitCode = $LASTEXITCODE",
    "  Refresh-Path",
    "  if (Test-CodexApp) { Ok 'Codex App installed'; return }",
    "  if ($exitCode -eq 0) { Ok 'Codex App installer completed; launch from Start menu if needed' } else { Fail 'Codex App' }",
    "}",
    "",
    "function Set-ClaudeCodeTelemetry {",
    "  param(",
    "    [string]$Endpoint, [string]$Protocol, [string]$HeaderName, [string]$HeaderValue, [string]$Environment, [string]$ResourceAttributes,",
    "    [string]$MetricInterval, [string]$LogsInterval, [string]$MetricsExporter, [string]$LogsExporter, [string]$TracesExporter,",
    "    [string]$LogPrompts, [string]$LogAssistant, [string]$LogToolDetails, [string]$LogToolContent, [string]$RawMode, [string]$RawDir",
    "  )",
    "  Step 'Claude Code CLI telemetry'",
    "  $combinedAttrs = \"deployment.environment=$Environment\"",
    "  if ($ResourceAttributes) { $combinedAttrs = \"$combinedAttrs,$ResourceAttributes\" }",
    "  $vars = @{",
    "    CLAUDE_CODE_ENABLE_TELEMETRY = '1'",
    "    OTEL_METRICS_EXPORTER = $MetricsExporter",
    "    OTEL_LOGS_EXPORTER = $LogsExporter",
    "    OTEL_EXPORTER_OTLP_PROTOCOL = $Protocol",
    "    OTEL_EXPORTER_OTLP_ENDPOINT = $Endpoint",
    "    OTEL_RESOURCE_ATTRIBUTES = $combinedAttrs",
    "    OTEL_METRIC_EXPORT_INTERVAL = $MetricInterval",
    "    OTEL_LOGS_EXPORT_INTERVAL = $LogsInterval",
    "    OTEL_LOG_USER_PROMPTS = $LogPrompts",
    "    OTEL_LOG_ASSISTANT_RESPONSES = $LogAssistant",
    "    OTEL_LOG_TOOL_DETAILS = $LogToolDetails",
    "    OTEL_LOG_TOOL_CONTENT = $LogToolContent",
    "    OTEL_TRACES_EXPORTER = $TracesExporter",
    "  }",
    "  if ($TracesExporter -ne 'none') { $vars.CLAUDE_CODE_ENHANCED_TELEMETRY_BETA = '1' }",
    "  if ($HeaderName -and $HeaderValue) { $vars.OTEL_EXPORTER_OTLP_HEADERS = \"$HeaderName=$HeaderValue\" }",
    "  if ($RawMode -eq 'inline') { $vars.OTEL_LOG_RAW_API_BODIES = '1' }",
    "  if ($RawMode -eq 'file' -and $RawDir) { $vars.OTEL_LOG_RAW_API_BODIES = \"file:$RawDir\" }",
    "  foreach ($entry in $vars.GetEnumerator()) {",
    "    [Environment]::SetEnvironmentVariable($entry.Key, $entry.Value, 'User')",
    "    Set-Item -Path \"Env:\\$($entry.Key)\" -Value $entry.Value",
    "  }",
    "  foreach ($name in @('CLAUDE_CODE_ENHANCED_TELEMETRY_BETA','OTEL_EXPORTER_OTLP_HEADERS','OTEL_LOG_RAW_API_BODIES')) {",
    "    if (-not $vars.ContainsKey($name)) { [Environment]::SetEnvironmentVariable($name, $null, 'User'); Remove-Item -Path \"Env:\\$name\" -ErrorAction SilentlyContinue }",
    "  }",
    "  Ok 'Claude Code telemetry configured'",
    "}",
    "",
    "function ConvertTo-TomlString([string]$Text) {",
    "  return $Text.Replace('\\', '\\\\').Replace('\"', '\\\"')",
    "}",
    "",
    "function ConvertTo-CodexExporterToml {",
    "  param([string]$Kind, [string]$Endpoint, [string]$Protocol, [string]$HeaderName, [string]$HeaderValue)",
    "  if (($Kind -eq 'none') -or ($Kind -eq 'statsig')) { return \"`\"$Kind`\"\" }",
    "  $safeEndpoint = ConvertTo-TomlString $Endpoint",
    "  $headers = ''",
    "  if ($HeaderName -and $HeaderValue) { $headers = ', headers = { \"' + (ConvertTo-TomlString $HeaderName) + '\" = \"' + (ConvertTo-TomlString $HeaderValue) + '\" }' }",
    "  if ($Protocol -eq 'grpc') { return \"{ otlp-grpc = { endpoint = `\"$safeEndpoint`\"$headers } }\" }",
    "  $httpProtocol = 'binary'",
    "  if ($Protocol -eq 'http/json') { $httpProtocol = 'json' }",
    "  return \"{ otlp-http = { endpoint = `\"$safeEndpoint`\", protocol = `\"$httpProtocol`\"$headers } }\"",
    "}",
    "",
    "function Set-CodexTelemetry {",
    "  param(",
    "    [string]$Endpoint, [string]$Protocol, [string]$HeaderName, [string]$HeaderValue, [string]$Environment, [string]$ResourceAttributes,",
    "    [string]$MetricInterval, [string]$LogsInterval, [string]$MetricsExporter, [string]$LogsExporter, [string]$TracesExporter,",
    "    [string]$LogPrompts, [string]$LogAssistant, [string]$LogToolDetails, [string]$LogToolContent, [string]$RawMode, [string]$RawDir,",
    "    [string]$CodexLogExporter, [string]$CodexTraceExporter, [string]$CodexMetricsExporter, [string]$CodexLogUserPrompt",
    "  )",
    "  Step 'Codex CLI telemetry'",
    "  $dir = Join-Path $env:USERPROFILE '.codex'",
    "  $config = Join-Path $dir 'config.toml'",
    "  $start = '# Dev Setup Builder - Codex telemetry start'",
    "  $end = '# Dev Setup Builder - Codex telemetry end'",
    "  try {",
    "    New-Item -ItemType Directory -Path $dir -Force -ErrorAction Stop | Out-Null",
    "    $content = if (Test-Path $config) { [IO.File]::ReadAllText($config, [Text.UTF8Encoding]::new($false)) } else { '' }",
    "    $clean = [regex]::Replace($content, \"(?ms)^$([regex]::Escape($start))\\r?\\n.*?^$([regex]::Escape($end))\\r?\\n?\", '')",
    "    if ($clean -match '(?m)^\\[otel\\]') { Warn 'Codex [otel] already exists outside Dev Setup Builder block; leaving it unchanged'; return }",
    "    $safeEnvironment = ConvertTo-TomlString $Environment",
    "    $logPrompt = if ($CodexLogUserPrompt -eq '1') { 'true' } else { 'false' }",
    "    $logExporterToml = ConvertTo-CodexExporterToml $CodexLogExporter $Endpoint $Protocol $HeaderName $HeaderValue",
    "    $traceExporterToml = ConvertTo-CodexExporterToml $CodexTraceExporter $Endpoint $Protocol $HeaderName $HeaderValue",
    "    $metricsExporterToml = ConvertTo-CodexExporterToml $CodexMetricsExporter $Endpoint $Protocol $HeaderName $HeaderValue",
    "    $block = @(",
    "      $start",
    "      '[otel]'",
    "      \"environment = `\"$safeEnvironment`\"\"",
    "      \"log_user_prompt = $logPrompt\"",
    "      \"exporter = $logExporterToml\"",
    "      \"trace_exporter = $traceExporterToml\"",
    "      \"metrics_exporter = $metricsExporterToml\"",
    "      $end",
    "      ''",
    "    )",
    "    [IO.File]::WriteAllText($config, ($clean.TrimEnd() + \"`r`n`r`n\" + ($block -join \"`r`n\")), [Text.UTF8Encoding]::new($false))",
    "  } catch { Fail \"Codex telemetry ($($_.Exception.Message))\"; return }",
    "  Ok 'Codex telemetry configured'",
    "}",
    "",
    "function Check-GitHubAuth {",
    "  Step 'GitHub CLI auth'",
    "  if (-not (Has-Command 'gh')) { Fail 'GitHub CLI auth (gh missing)'; return }",
    "  & gh auth status *>> $LogFile",
    "  if ($LASTEXITCODE -eq 0) { Ok 'GitHub CLI authenticated' } else { Warn 'GitHub CLI not authenticated. Run: gh auth login -w' }",
    "}",
    "",
    "function Install-CodeExtension {",
    "  param([string]$ExtensionId, [string]$Label)",
    "  Step $Label",
    "  if (-not $script:vscodeCmd) { $script:vscodeCmd = Find-Code }",
    "  if (-not $script:vscodeCmd) { Fail \"$Label (VS Code missing)\"; return }",
    "  $extensions = & $script:vscodeCmd --list-extensions 2>$null",
    "  if ($extensions -match [regex]::Escape($ExtensionId)) { Ok \"$Label installed\"; return }",
    "  & $script:vscodeCmd --install-extension $ExtensionId --force *>> $LogFile",
    "  $extensions = & $script:vscodeCmd --list-extensions 2>$null",
    "  if ($extensions -match [regex]::Escape($ExtensionId)) { Ok \"$Label installed\" } else { Fail $Label }",
    "}",
    "",
    "function Set-GitDefaults {",
    "  param([string]$Name, [string]$Email)",
    "  Step 'Git identity defaults'",
    "  if (-not (Has-Command 'git')) { Fail 'Git identity defaults (git missing)'; return }",
    "  $existingName = & git config --global user.name 2>$null",
    "  $existingEmail = & git config --global user.email 2>$null",
    "  if ($existingName -and $existingEmail) { Ok 'Git identity already set'; return }",
    "  if (-not $existingName) { & git config --global user.name $Name *>> $LogFile }",
    "  if (-not $existingEmail) { & git config --global user.email $Email *>> $LogFile }",
    "  Ok 'Git identity defaults set'",
    "}",
    "",
    "Refresh-Path",
    "",
    ...body,
    "",
    "Write-Host \"\"",
    "Write-Host \"Log: $LogFile\"",
    "if ($script:Failed.Count -gt 0) {",
    "  Write-Host 'Failed items:'",
    "  foreach ($item in $script:Failed) { Write-Host \"  - $item\" }",
    "  exit 1",
    "}",
    "Write-Host 'Done. Open a new terminal before using newly installed commands.'",
    "exit 0"
  ].join("\r\n");
}

export function buildScript(ids, os, settings) {
  const resolved = resolveSelection(ids, os);
  return os === "mac" ? buildMacScript(resolved, settings) : buildWindowsScript(resolved, settings);
}

export function permissionHelp(os) {
  return os === "mac" ? [
    "Run with bash setup-mac.command if the download is not executable.",
    "For Finder double-click, run chmod +x setup-mac.command first.",
    "If macOS blocks it, right-click the file, choose Open, then Open again.",
    "If quarantine still blocks it, run xattr -d com.apple.quarantine setup-mac.command."
  ] : [
    "If Windows blocks the file, right-click it, open Properties, then check Unblock.",
    "If installers fail, right-click setup-windows.bat and choose Run as administrator.",
    "If SmartScreen appears, choose More info, then Run anyway.",
    "PowerShell policy is bypassed only for this script run."
  ];
}

export function presetSelection(name) {
  if (name === "clear") {
    return new Set();
  }
  return new Set(PACKAGES.filter((item) => item.presets.includes(name)).map((item) => item.id));
}

export function selfTest() {
  const settings = { gitName: "A", gitEmail: "a@example.com" };
  const selected = new Set(["codex-app", "codex", "claude-extension"]);
  const mac = resolveSelection(selected, "mac");
  const win = resolveSelection(selected, "win");
  const macScript = buildMacScript(mac, settings);
  const winScript = buildWindowsScript(win, settings);
  const setupSelected = new Set(["pnpm", "github-auth", "wsl2"]);
  const macSetup = resolveSelection(setupSelected, "mac");
  const winSetup = resolveSelection(setupSelected, "win");
  const macSetupScript = buildMacScript(macSetup, settings);
  const winSetupScript = buildWindowsScript(winSetup, settings);
  const codexOnlyScript = buildMacScript(resolveSelection(new Set(["codex"]), "mac"), settings);
  const nodeIndex = codexOnlyScript.indexOf('brew_formula "Node.js"');
  const codexCallIndex = codexOnlyScript.lastIndexOf("install_codex_cli");
  const codexNativeIndex = codexOnlyScript.indexOf("https://chatgpt.com/codex/install.sh");
  const codexBrewIndex = codexOnlyScript.indexOf("brew install --cask codex");
  const codexNpmIndex = codexOnlyScript.indexOf('npm_global "Codex CLI"');
  const claudeOnlyScript = buildMacScript(resolveSelection(new Set(["claude-code"]), "mac"), settings);
  const claudeNativeIndex = claudeOnlyScript.indexOf("https://claude.ai/install.sh");
  const claudeBrewIndex = claudeOnlyScript.indexOf("brew install --cask claude-code");
  const claudeNpmIndex = claudeOnlyScript.indexOf('npm_global "Claude Code CLI"');
  const checks = [
    mac.has("node"),
    mac.has("vscode"),
    mac.has("homebrew"),
    win.has("node"),
    win.has("vscode"),
    macSetup.has("node"),
    macSetup.has("gh"),
    macSetup.has("homebrew"),
    !macSetup.has("wsl2"),
    winSetup.has("node"),
    winSetup.has("gh"),
    winSetup.has("wsl2"),
    macScript.includes("@openai/codex"),
    macScript.includes("https://persistent.oaistatic.com/codex-app-prod/Codex.dmg"),
    macScript.includes("anthropic.claude-code"),
    winScript.includes("@openai/codex"),
    winScript.includes("9PLM9XGG6VKS"),
    winScript.includes("Install-CodexApp"),
    winScript.includes("anthropic.claude-code"),
    buildMacScript(resolveSelection(new Set(["claude-code-telemetry"]), "mac"), settings).includes("CLAUDE_CODE_ENABLE_TELEMETRY=1"),
    buildMacScript(resolveSelection(new Set(["codex-telemetry"]), "mac"), settings).includes("[otel]"),
    buildWindowsScript(resolveSelection(new Set(["claude-code-telemetry"]), "win"), settings).includes("CLAUDE_CODE_ENABLE_TELEMETRY"),
    buildWindowsScript(resolveSelection(new Set(["codex-telemetry"]), "win"), settings).includes("Set-CodexTelemetry"),
    macSetupScript.includes("install_pnpm"),
    macSetupScript.includes("check_github_auth"),
    !macSetupScript.includes("WSL2"),
    winSetupScript.includes("Install-Pnpm"),
    winSetupScript.includes("Check-GitHubAuth"),
    winSetupScript.includes("Install-WSL2"),
    nodeIndex >= 0 && nodeIndex < codexCallIndex,
    codexNativeIndex >= 0 && codexNativeIndex < codexBrewIndex && codexBrewIndex < codexNpmIndex,
    claudeNativeIndex >= 0 && claudeNativeIndex < claudeBrewIndex && claudeBrewIndex < claudeNpmIndex,
    buildMacScript(new Set(["homebrew", "docker"]), settings).includes('brew_cask "Docker Desktop" "docker"'),
    buildWindowsScript(new Set(["docker"]), settings).includes("Docker.DockerDesktop")
  ];
  return { ok: checks.every(Boolean), checks };
}
